server:
  port: 9898 # Updated to match Docker Compose

spring:
  application:
    name: hedgeservice
  threads:
    virtual: { enabled: true }

  # --- REDIS CONFIG ---
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 10m
  # --------------------

  datasource:
    url: jdbc:postgresql://localhost:5432/analyticsandtrading
    username: ${DB_USER} # Removed insecure default
    password: ${DB_PASS} # Removed insecure default
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      read-only: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/trading-realm
          jwk-set-uri: http://keycloak:8080/realms/trading-realm/protocol/openid-connect/certs

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"