version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analyticsandtrading
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    ports: ["9092:9092"]

  positionloader:
    build:
      context: ./positionloader
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_USER: postgres
      DB_PASS: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/analyticsandtrading
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports: ["8080:8080"]
    depends_on: [postgres, kafka]

volumes:
  pgdata: