global:
  scrape_interval: 5s
rule_files:
  - "/etc/prometheus/prometheus-rules.yaml" # <--- ADD THIS
scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080', 'positionloader:8080', 'priceservice:8080']