server:
  port: 8080

spring:
  application:
    name: gateway
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          max-wait: 500ms

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8180}/realms/trading-realm
          jwk-set-uri: ${KEYCLOAK_URI:http://localhost:8180}/realms/trading-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://trade.morganstanley.com", "http://localhost:3000"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: [Authorization, Content-Type, App-ID]
            allowCredentials: true

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

      default-filters:
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 200
            key-resolver: "#{@userKeyResolver}"
        - name: Retry
          args: { retries: 3, methods: GET }

      routes:
        - id: position-loader
          uri: http://positionloader:8080
          predicates: [ Path=/api/loader/** ]
          filters:
            - name: CircuitBreaker
              args: { name: loaderCircuitBreaker, fallbackUri: forward:/fallback/loader }

        - id: hedge-service
          uri: http://hedgeservice:8080
          predicates: [ Path=/api/hedge/** ]
          filters:
            - name: CircuitBreaker
              args: { name: hedgeCircuitBreaker, fallbackUri: forward:/fallback/hedge }

        - id: price-service-ws
          uri: ws://priceservice:8080
          predicates: [ Path=/ws-market-data/** ]

        - id: trade-processor
          uri: http://tradefillprocessor:8080
          predicates: [ Path=/api/trades/** ]

# SECURITY: Lockdown Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus" # Block 'env', 'heapdump', 'beans'
  endpoint:
    health:
      show-details: when_authorized # Only admins see full stack traces