server:
  port: 8080

spring:
  application:
    name: gateway
  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8180}/realms/trading-realm
          jwk-set-uri: ${KEYCLOAK_URI:http://localhost:8180}/realms/trading-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
        - TokenRelay
        # THE SHIELD: Global Rate Limit (100 req/sec per user)
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 200
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@userKeyResolver}"

      routes:
        - id: position-loader
          uri: http://positionloader:8080
          predicates:
            - Path=/api/loader/**
        - id: hedge-service
          uri: http://hedgeservice:8080
          predicates:
            - Path=/api/hedge/**
        - id: price-service-ws
          uri: ws://priceservice:8080
          predicates:
            - Path=/ws-market-data/**
        - id: trade-processor
          uri: http://tradefillprocessor:8080
          predicates:
            - Path=/api/trades/**

logging:
  level:
    org.springframework.cloud.gateway: INFO

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"