server:
  port: 8081 # Mock runs on 8081

spring:
  application:
    name: mock-upstream
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # Clean JSON for interoperability